spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cms.cristik.win:3306/cms_test
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
