management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    refresh:
      enabled: true

spring:
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://gitee.com/cristik/git-config.git
          #配置目录
          search-paths: '{application}'
          #
          default-label: master
          force-pull: true
          deleteUntrackedBranches: true
          # 更新频率单位秒
          refresh-rate: 30
          username: cristik1991@gamil.com
          password: xxxxx
      request-connect-timeout: 5
      request-read-timeout: 3